### ISSUE TITLE
code request

### ISSUE THREAD

**Issue by zhaozhengyang01** [jyicu/DPDN#2]
I hope this email finds you well. I recently came across your research paper titled Dual Path Denoising Network for Real
Photographic Noise and was thoroughly impressed with the quality of your work. Furthermore, I discovered the corresponding code repository on GitHub, which includes the pre-trained models.

However, I am facing some difficulties as the training code is not available in the repository. As I am keen on understanding the entire training process and potentially implementing modifications for my own research, I kindly request your assistance in providing the complete training code for DPDN.

Having access to the training code would greatly benefit my understanding and enable me to reproduce your results effectively. I assure you that I will strictly adhere to any licensing terms or usage restrictions associated with the code.

Thank you for your attention to this matter. I genuinely appreciate your contribution to the research community, and I look forward to your positive response.

Sincerely,
zhaozhengyang
zhaozhengyang611@gmail.com

**Comment by jyicu** [comment]
Hi, zhaozhengyang
Thank you for your patience, and I apologize for my delayed response.
I've uploaded the training code; however, I'd like to mention that this code is from three years ago, and as a result, it may not seamlessly align with the current published version. Please consider using this code as a reference and adapt it as necessary to fit your needs.
For guidance on preparing the dataset, you can refer to the guidelines provided at https://github.com/jyicu/CBSN.

Best regards,
Yeong Il Jang
